kind: pipeline
name: int-sqlite-callapi

steps:
  - name: integration-callapi
    image: nextcloudci/php7.1:php7.1-16
    environment:
      APP_NAME: spreed
      CORE_BRANCH: master
      DATABASEHOST: sqlite
    commands:
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DATABASEHOST
      - cd ../server
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run integration tests
      - cd tests/integration/
      - bash run.sh features/callapi

services:
  - name: cache
    image: redis

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: int-mysql-callapi

steps:
  - name: integration-callapi
    image: nextcloudci/php7.1:php7.1-16
    environment:
      APP_NAME: spreed
      CORE_BRANCH: master
      DATABASEHOST: mysql
    commands:
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DATABASEHOST
      - cd ../server
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run integration tests
      - cd tests/integration/
      - bash run.sh features/callapi

services:
  - name: cache
    image: redis
  - name: mysql
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: owncloud
      MYSQL_USER: oc_autotest
      MYSQL_PASSWORD: owncloud
      MYSQL_DATABASE: oc_autotest
    command: [ "--innodb_large_prefix=true", "--innodb_file_format=barracuda", "--innodb_file_per_table=true" ]
    tmpfs:
      - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
    - integration/*
  event:
#    - pull_request
    - push

---
kind: pipeline
name: int-pgsql-callapi

steps:
  - name: integration-callapi
    image: nextcloudci/php7.1:php7.1-16
    environment:
      APP_NAME: spreed
      CORE_BRANCH: master
      DATABASEHOST: pgsql
    commands:
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DATABASEHOST
      - cd ../server
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run integration tests
      - cd tests/integration/
      - bash run.sh features/callapi

services:
  - name: cache
    image: redis
  - name: pgsql
    image: postgres:10
    environment:
      POSTGRES_USER: oc_autotest
      POSTGRES_DB: oc_autotest_dummy
      POSTGRES_PASSWORD:
    tmpfs:
      - /var/lib/postgresql/data

trigger:
  branch:
    - master
    - stable*
      - integration/*
  event:
#    - pull_request
    - push
